#include <steam_api.h>
#include <steam_gameserver.h>

static const char STEAMAPI_GAMESERVER_INITEX_INTERFACES[] =
    STEAMUTILS_INTERFACE_VERSION "\0"
    STEAMNETWORKINGUTILS_INTERFACE_VERSION "\0"
    STEAMGAMESERVER_INTERFACE_VERSION "\0"
    STEAMGAMESERVERSTATS_INTERFACE_VERSION "\0"
    STEAMHTTP_INTERFACE_VERSION "\0"
    STEAMINVENTORY_INTERFACE_VERSION "\0"
    STEAMNETWORKING_INTERFACE_VERSION "\0"
    STEAMNETWORKINGMESSAGES_INTERFACE_VERSION "\0"
    STEAMNETWORKINGSOCKETS_INTERFACE_VERSION "\0"
    STEAMUGC_INTERFACE_VERSION "\0"
    "\0";
